Pass tests of FindMeetingQueryTests.java
alexanderlopez/calendar_project pull request #1
Opened 2020-07-13 23:56 UTC by alexanderlopez

2020-07-14 16:09 UTC, salehhamadeh requested changes

2020-07-14 16:09 UTC, salehhamadeh commented on src/main/java/com/google/sps/FindMeetingQuery.java
> +    private void removeSmallSlots(ArrayList<TimeRange> timeList, long duration) {
"Parameters are most naturally interpreted as inputs to a function. As a result, output parameters are unexpected, which makes code harder to understand at first glance."

timeList is used as an output parameter here. A better approach would be to not mutate the parameter but to create a new list and return it, similar to Java's String.trim() method. If you do that, you wouldn't have to call clone, which would actually make your method more performant.

So you would call this method as follows:
`returnList = removeSmallSlots(returnList, request.getDuration());`

2020-07-14 16:09 UTC, salehhamadeh commented on src/main/java/com/google/sps/FindMeetingQuery.java
> +    private void trimList(ArrayList<TimeRange> timeList, Collection<String> participants,
Same comment here. Prefer immutable parameters.

2020-07-15 22:22 UTC, Felomeng approved these changes

2020-07-15 22:22 UTC, Felomeng commented on src/main/java/com/google/sps/FindMeetingQuery.java
> +                new PriorityQueue<Event>(new Comparator<Event>() {
Could use lambda:
https://leetcode.com/problems/top-k-frequent-elements/discuss/156845/java-priority-queue-lambda-expression

2020-07-15 22:22 UTC, Felomeng commented on src/main/java/com/google/sps/FindMeetingQuery.java
> +            TimeRange currentEvent = eventQueue.poll().getWhen();
rename currentEvent to something like currentEventTimeRange as it is not an event

2020-07-15 23:00 UTC, salehhamadeh approved these changes
Looks good!

2020-07-16 19:25 UTC, merged